### ISSUE TITLE
mysql_numrows for php4 code

### ISSUE THREAD

**Issue by dafuki** [kitserve/php7-compat#1]
mysql_numrows (not num_rows) is still used in some very old code.
Maybe consider adding a wrapper to it, too?

**Comment by kitserve** [comment]
Thanks for the suggestion. Your contribution would be welcome if you want to write it! Otherwise I'll try to put that in when I have time, but can't see it happening soon.

**Comment by dafuki** [comment]
Not really used to working with github, but I have created a pull request.

**Comment by dafuki** [comment]
fixed in https://github.com/kitserve/php7-compat/commit/92ad129d97d02534f28c441f4d6a27e2630702ed
