### ISSUE TITLE
ereg functions and split(i) should use addcslashes, not preg_quote

### ISSUE THREAD

**Issue by Martinique** [kitserve/php7-compat#6]
As it is now, `preg_quote` escapes regular expressions into normal strings, which won't work, of course. The fix is simply to replace all instances of `preg_quote` with `addcslashes` so that only slashes are escaped for `preg_*` functions. Function arguments remain the same.

**Comment by kitserve** [comment]
Thanks for pointing this out. This is now fixed. I've used `mb_ereg_replace()` instead of `addcslashes()` because it's multibyte-encoding safe.

**Comment by Martinique** [comment]
Are you sure you didn't just create another (rare) problem in which a multibyte character might contain a byte that is a slash, which `mb_ereg_replace()` can't fix? You might want to do some testing.

**Comment by kitserve** [comment]
Surely that will only be an issue in the case that the string is in a different encoding to PHP's current encoding? I'm not sure there's any way of reliably protecting against invalid characters while avoiding mangling valid data unless the character encoding is correctly set. Admittedly in that case I'm not too sure what the behaviour would have been under the original PHP 5 versions of these functions, perhaps mangling is to be expected.
